### ISSUE TITLE
To short

### ISSUE THREAD

**Issue by GooglyTank** [Zer0-Official/Red-is-Bad#1]
The game is to short make a sequel with a story and more levels I already have a name "Black is Bad!!" you could play as a white square instead since black would be the enemy this time.

**Comment by GooglyTank** [comment]
also its way to hard I had to cheat to win

**Comment by Zer0-Official** [comment]
You didn't *have* to cheat to win. You chose to because it seems that you are too lazy to actually play and enjoy the game. If you think the game is too difficult, fix it and open a pull request.
